Home courses integration
serojascardenas/e-learning_platform pull request #11
Opened 2022-01-16 05:33 UTC by serojascardenas

2022-01-16 14:11 UTC, HernanCote requested changes

2022-01-16 14:11 UTC, HernanCote commented on backend/routes/courses/index.js
> +	routes.get('/filter',
Como se está pasando el filtro por un query param, creo que esta ruta no es necesaria. Por lo cual podrías implementar el filtro dentro de la ruta base de /courses

2022-01-16 14:11 UTC, HernanCote commented on ui/package.json
> -    "axios": "^0.24.0",
Por que borras axios y joi-browser? Los estamos utilizando

2022-01-16 14:11 UTC, HernanCote commented on ui/src/actions/courses.js
> +	return response.data;
Esto lo puedes borrar ya que el diapatch se encarga de retornar la data

2022-01-16 14:11 UTC, HernanCote commented on ui/src/components/Navbar/Navbar.jsx
> +								<Button variant="secondary" onClick={()=>onSubmit()}>Iniciar Sesión</Button>
Por que hacer el fetch de los cursos nuevamente? Si se supone que ya los tienes desde el home.

2022-01-16 14:11 UTC, HernanCote commented on ui/src/pages/Home/index.jsx
> +			let courses = await dispatch(getAllCourses());
No es necesario utilizar await con dispatch ya que redux-thunk se encarga de eso, por eso se configuró en el store.

2022-01-17 04:39 UTC, closed without merging

2022-01-17 04:40 UTC, serojascardenas commented on backend/routes/courses/index.js
> +	routes.get('/filter',
Modificado

2022-01-17 04:41 UTC, serojascardenas commented on ui/package.json
> -    "axios": "^0.24.0",
Sigue ahí pero se aumento una dependencia y se movió en el archivo

2022-01-17 04:41 UTC, serojascardenas commented on ui/src/actions/courses.js
> +	return response.data;
si le puedes modificar porque aun no entiendo bien su uso

2022-01-17 04:42 UTC, serojascardenas commented on ui/src/components/Navbar/Navbar.jsx
> +								<Button variant="secondary" onClick={()=>onSubmit()}>Iniciar Sesión</Button>
esto era una prueba, está borrado

2022-01-17 04:42 UTC, serojascardenas commented on ui/src/pages/Home/index.jsx
> +			let courses = await dispatch(getAllCourses());
si puedes modificar el código xq de otro modo no me funciona